config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'homepage#index'

  get 'profile' => 'profile#index'

  get 'dashboard' => 'dashboard#index'

  resources :survey, only: [:show]

end

app/models/survey.rb
class Survey < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected

  def configure_devise_permitted_parameters
    registration_params = [:full_name, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end
  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	def index
		@surveys = Survey.all
	end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
	def index

	end

end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
	def index

	end

end

app/controllers/survey_controller.rb
class SurveyController < ApplicationController
	def show
		@survey = Survey.find(params[:id])
	end

	def create
	end

	def index
	end

	def new
	end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
	def index

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<% if user_signed_in? %>

<h1>Welcome to your dashboard <%= current_user.full_name %>!</h1>

<% for survey in @surveys do %>
<%= link_to "#{survey.title}", survey_path(survey.id) %>
<br>
<% end %>
<%= link_to "Build your Profile", profile_path %>
<%= link_to "Log Out", destroy_user_session_path, method: :delete %>


<% else %>
<h1>You should not be here, 404?</h1>

<% end %>

app/views/homepage/index.html.erb
<% if user_signed_in? %>

<h1>You signed in <%= current_user.full_name %>!</h1>


<%= link_to "Build your Profile", profile_path %>
<%= link_to "Dashboard", dashboard_path %>
<%= link_to "Log Out", destroy_user_session_path, method: :delete %>


<% else %>
<h1>Hello! Welcome go DP! Please sign up below, or else... </h1>
<br>
<h1><%= link_to "Sign Up", new_user_registration_path %></h1>
<h1><%= link_to "Sign In", new_user_session_path %></h1>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DartPoll</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/survey/show.html.erb
<%= @survey.title %>
<div class="order-header-container">
		
		<div class="order-header">box order form</div>
	</div>
	<div class="order-form-container">
		<div class="order-form-content-container">
			<div class="order-form-header">Contact info:</div>
			<form action="/order" class="order-form" method="post">
			 <input type="text" name="name" placeholder="full name">
			 <br>
			 <input type="text" name="email" placeholder="email">
			 <br>
			 <input type="text" name="phone" placeholder="phone number">
			 <br>
			 <div class="order-form-header">Select your box:</div>
			 <br>
			 <div class="row">
			 	<div class="four columns">
					 <input type="checkbox" name="produce_box" value="produce">
					 	<div class="produce-box-header">produce box $10</div><br>
					 	<div class="produce-box-body">Green Peas, Salad Mix, Asian Pears</div>
					 <br>
				</div>
				<div class="four columns">
					 <input type="checkbox" name="snack_box" value="snack">
					 	<div class="produce-box-header">snack box $10</div><br>
					 	<div class="produce-box-body">Snow Peas, Carrots, Concord Grapes</div>
					 <br>
				</div>
			 </div>
			 <div class="order-form-header">Add items a la carte:</div>
			 <br>
			 <div class="row">
			 	<div class="four columns">
					 <input type="checkbox" name="ad1" value="Beef"><div class="produce-box-header">"Add-On 1" ($6.50)</div><br><div class="produce-box-body">Pasture Ground Beef</div>
				</div>
				<div class="four columns">
					 <input type="checkbox" name="ad2" value="Cider"><div class="produce-box-header">"Add-On 2" ($4.50)</div><br>
					 <div class="produce-box-body">1/2 Gallon Cider</div>
				</div>
				<div class="four columns">
					 <input type="checkbox" name="ad3" value="Granola"><div class="produce-box-header">"Add-On 3" ($4.50)</div><br><div class="produce-box-body">Savory and Healthy Granola (Shady Lane)</div>
				</div>
			</div>
			<div class="row">
				<div class="four columns">
					 <input type="checkbox" name="ad4" value="Eggs"><div class="produce-box-header">"Add-On 4" ($2.50)</div><br><div class="produce-box-body">1/2 Dozen Eggs</div>
				</div>
				<div class="four columns">
					 <input type="checkbox" name="ad5" value="Pears"><div class="produce-box-header">"Add-On 5" ($3)</div><br><div class="produce-box-body">3 Asian Pears</div>
				</div>
				<div class="four columns">
					 <input type="checkbox" name="ad6" value="Grapes"><div class="produce-box-header">"Add-On 6" ($3.50)</div><br><div class="produce-box-body">1/2 Quart Concord Grapes</div>
				</div>
			 </div>
			 <div class="alert">***Please be aware that, due to the local, organic nature of our food, some last-minute swaps may be necessary to accommodate unexpected changes in availability</div>
			 <div class="order-form-header">Comments:</div>
			 <br>
			 <div>please specify any dietary restrictions so we may accomodate you</div><br>
			 <textarea></textarea>
			 <br>
			 <div class="alert">If you are ordering a box using a discount code, please select either the snack option only. Other options are unavailable via discount code at this time, but they are coming soon!</div>
			 <div class="order-form-header">Discount code:</div>
			 <br>
			 <input type="text" name="discount_code">
			 <div class="order-form-header">Questions?</div>
			 <br>
			 <div class="order-form-questions">If you have any questions about your order, please feel free to contact us at <strong><%= mail_to "greenstogrounds@gmail.com", "greenstogrounds@gmail.com"%></strong></div>
			 <br><br>
			 <div class="alert">***Please note: When you hit the submit order button, you will be taken to PayPal. If you are experiencing problems with PayPal you may pay through Venmo (@greenstogrounds). If we do not receive a payment on either of those platforms by Wednesday at noon your order will not be complete and you will not receive your box.</div>
			 <br>
			 <input type="image" value="Submit" src="/assets/submit.png">
			</form>
		</div>
	</div> 